version: '3'
services:
  jenkins:
    build: ./jenkins
    ports:
      - "50000:50000"
    privileged: true
    user: root
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
        - JENKINS_OPTS="--prefix=/tools/jenkins"
        - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    networks:
      - jenkins-net
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - jenkins-net

volumes:
  jenkins-data:
  jenkins-log:
networks:
  jenkins-net:
