version: '3'
services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jenkins
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - '8080:8080'
    volumes:
      - ./jenkins_home:/var/jenkins_home
