version: "3"
services:
  jenkins:
      image: jenkins-master
      build:
        context: .
        dockerfile: ./Dockerfile
      privileged: true
      user: root
      ports:
        - 8080:8080
        - 50000:50000
      container_name: jenkins
      volumes:
        - jenkins-storage:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - JENKINS_OPTS="--prefix=/jenkins/tools"
        - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
  newrelic-agent-jarvis:
    container_name: newrelic-infra-jenkins-master
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      NRIA_LICENSE_KEY: "775a9070fcd55c875aba28e6d4b970d11629NRAL"
    restart: unless-stopped
  nginx-jarvis:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/var/www/html/index.html
    depends_on:
      - jenkins
volumes:
  jenkins-storage: