version: "3"
services:
  nginx-jarvis:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html