version: "3"
services:
  nginx-jarvis:
    image: nginx:latest
    container_name: nginx-jarvis
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "jenkins:129.213.22.70"